### ISSUE TITLE
Gestures not working

### ISSUE THREAD

**Issue by magnus-gross** [Coffee2CodeNL/gebaar-libinput#12]
I cannot get the gestures to work.

I have installed the AUR package and added a config file at `~/.config/gebaar/gebaard.toml` with the content:

```toml
[commands.swipe.three]
up = "xdotool key ctrl+F10"
down = "xdotool key ctrl+F8"
left = "qdbus org.kde.KWin /KWin previousDesktop"
right = "qdbus org.kde.KWin /KWin nextDesktop"
```

I am also in the input group (I was using libinput-gestures before).

Now, when I run `gebaard`, I cannot get it to recognize any three finger swipe motion. It sometimes outputs:

```
libinput error: event12 - ETPS/2 Elantech Touchpad: kernel bug: Touch jump detected and discarded.
See https://wayland.freedesktop.org/libinput/doc/1.12.6/touchpad-jumping-cursors.html for details
```

But I think, that this is unrelated. Since there is no verbose test mode, I cannot test if it is not detecting my gestures or if something is wrong with my config file.

**Comment by anowlcalledjosh** [comment]
Likewise – I had to make a few modifications to get it to compile on Ubuntu 18.04 (remove the minimum CMake version, replace `filesystem` with `experimental/filesystem`), but it doesn't appear to be doing anything.

It does seem to be able to recognise gestures; when I do a swipe, it will print the string `83c9f035e`. But I don't know why it does that, and it doesn't run any of the commands in the config file.

**Comment by Coffee2CodeNL** [comment]
> Likewise – I had to make a few modifications to get it to compile on Ubuntu 18.04 (remove the minimum CMake version, replace `filesystem` with `experimental/filesystem`), but it doesn't appear to be doing anything.

You're using GCC7, use GCC8.

**Comment by anowlcalledjosh** [comment]
> use GCC8

Thanks, that makes it compile without changes, apart from the cmake version. Now it prints `Error: target STRING not available` whenever it detects a gesture.

**Comment by Coffee2CodeNL** [comment]
Use this as config file template: 

```toml
[commands.swipe.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""

[commands.swipe.four]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""
```
